"""Render the command reference from `alphaengine.commands`.

    python scripts/gen_docs.py            # print the markdown block
    python scripts/gen_docs.py --write    # splice it into README.md
    python scripts/gen_docs.py --check    # fail if README.md is stale

── WHY THIS EXISTS ────────────────────────────────────────────────────────────

The command list lived in three hand-maintained places and none of them agreed:
the REPL's help text, the README, and the docs page on the site. `--data` and
`--universe` shipped and appeared in one; the docs page listed no CLI commands
at all. Every copy looks authoritative on its own, so a reader who finds the
stale one concludes the feature does not exist.

`--check` runs in CI. A verb added to `commands.py` and forgotten in the README
fails a build rather than quietly misleading somebody for a month.

The block is delimited by HTML comments so the rest of the README stays
hand-written. Generating a whole README produces something nobody wants to read;
generating the one part that is a machine-readable list is the whole trick.
"""

from __future__ import annotations

import argparse
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1] / "src"))

from alphaengine.commands import COMMANDS, DATA_DOORS, FLAGS, GROUPS  # noqa: E402

START = "<!-- COMMANDS:START -->"
END = "<!-- COMMANDS:END -->"
README = pathlib.Path(__file__).resolve().parents[1] / "README.md"


def _sig(c) -> str:
    return f"{c.verb} {c.args}".strip()


def _cell(text: str) -> str:
    """A pipe inside a markdown table cell ends the cell.

    `key [quantos | anthropic | openai]` renders as three broken columns
    otherwise, which is the sort of thing a generator is supposed to make
    impossible rather than reproduce faithfully.
    """
    return text.replace("|", "\|")


def render() -> str:
    out: list[str] = [
        START,
        "<!-- Generated by scripts/gen_docs.py from src/alphaengine/commands.py.",
        "     Do not edit by hand; run `python scripts/gen_docs.py --write`. -->",
        "",
    ]

    for group, title in GROUPS:
        rows = [c for c in COMMANDS if c.group == group]
        if not rows:
            continue
        out += [f"### {title}", "", "| Command | Does | Where |", "|---|---|---|"]
        for c in rows:
            where = {"both": "shell + session", "cli": "shell", "repl": "session"}[c.scope]
            out.append(f"| `{_cell(_sig(c))}` | {_cell(c.purpose)} | {where} |")
        out.append("")

    out += [
        "### Data flags",
        "",
        "| Flag | What it takes |",
        "|---|---|",
    ]
    for door, what in DATA_DOORS:
        out.append(f"| `{_cell(door)}` | {_cell(what)} |")
    out.append("")

    out += ["### Flags", "", "| Flag | Does |", "|---|---|"]
    for f in FLAGS.values():
        sig = f"{f.name} {f.takes}".strip()
        out.append(f"| `{_cell(sig)}` | {_cell(f.purpose)} |")
    out.append("")

    # Every command that carries examples, so the reference is copy-pasteable
    # rather than a signature list somebody has to guess their way through.
    out += ["### Examples", "", "```bash"]
    for c in COMMANDS:
        for ex in c.examples:
            if ex.startswith("alphaengine"):
                out.append(ex)
    out += ["```", "", END]
    return "\n".join(out)


def splice(text: str, block: str) -> str:
    if START not in text or END not in text:
        raise SystemExit(
            f"README.md has no {START} / {END} markers. Add them where the command reference should live."
        )
    head = text.split(START)[0]
    tail = text.split(END, 1)[1]
    return head + block + tail


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--write", action="store_true", help="splice into README.md")
    ap.add_argument("--check", action="store_true", help="fail if README.md is stale")
    args = ap.parse_args()

    block = render()

    if args.write:
        README.write_text(splice(README.read_text(encoding="utf-8"), block), encoding="utf-8")
        print(f"wrote {README}")
        return 0

    if args.check:
        current = README.read_text(encoding="utf-8")
        if splice(current, block) != current:
            print(
                "README.md's command block is stale.\n"
                "  A verb changed in src/alphaengine/commands.py and the README did not.\n"
                "  Run: python scripts/gen_docs.py --write",
                file=sys.stderr,
            )
            return 1
        print("README command block is current")
        return 0

    print(block)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
